### ISSUE TITLE
grunt-sass instead grunt-contrib-sass

### ISSUE THREAD

**Issue by blackout314** [brunoscopelliti/marvin#11]
For improve performance you can use grunt-sass (libsass) instead of grunt-contrib-sass (ruby). Need real OS (not windows i think) for compile libsass :-)
libsass is fast and use less cpu

**Comment by brunoscopelliti** [comment]
Hi @blackout314 ,

the report is now completed... we do not use sass so often now... so we do not need to speed up things...

moreover if windows does not support libsass, as you can imagine, libsass is not a solution for us.

best regards!
