### ISSUE TITLE
Screen size

### ISSUE THREAD

**Issue by aberonni** [brunoscopelliti/marvin#12]
Possibility to open the browser window in a customizable screen size set from config file.

**Comment by brunoscopelliti** [comment]
It's available a config.json property, **screenSize**, that permits to customize the screen size of the browser at the start of a test:

```
// from config.json

{
  "baseUrl": "****",
  ...
  "screenSize": { "x": 1024, "y": 768 },
  "browsers": [{
  }]
}
```


In case screenSize is not defined the default behaviour is to meximize the browser size.

**Comment by verlok** [comment]
Can I suggest "w" and "h" as properties? X and Y often refer to a point, instead of a size. W and H would mean width and height.

**Comment by brunoscopelliti** [comment]
I think that the name of the object (**screenSize**) to which they belong, makes clear enough their meaning.
