### ISSUE TITLE
Reports tabs don't work in some cases

### ISSUE THREAD

**Issue by verlok** [brunoscopelliti/marvin#8]
Reports tabs fail to work when the browser or the OS contain "special" characters like ` ` or `.`.
The problem is the that the tab ids are `#OS X 10.11safari8.1` or `#Windows XPinternet explorer8.0`.

**Comment by alaiaf** [comment]
With the following configuration, the switch between the tabs of the report for Safari doesn't work:
{
    "baseUrl": "http://www.yoox.com",
    "featuresDir": "tests/features",
    "stepsDir": "tests/steps",
    "resultsDir": "results",
    "dictionaryFile": "tests/dict.json",
    "reporter": "marvin",
    "threads": 1,
    "clean": false,
    "verbose": true,
    "stepDelay": 1500,
    "testTimeout": 50000,
    "elementTimeout": 15000,
    "tags": "@dev",
    "browsers": [{
        "browserName": "chrome",
        "chromeOptions": {
            "args": ["--no-sandbox"]
        }
    }, {
        "browserName": "firefox"
    }, {
        "seleniumServer": "http://hub.browserstack.com/wd/hub",
        "browserstack.user": "andreaverlicchi2",
        "browserstack.key": "p9XyhTBXws3wHqVEHFjX",
        "os": "OS X",
        "os_version": "Yosemite",
        "browserName": "safari",
        "browser": "Safari",
        "browser_version": "8"
    }, {
        "seleniumServer": "http://ondemand.saucelabs.com:80/wd/hub",
        "username": "andreaverlicchi_yoox",
        "accessKey": "b9890f14-ad14-4ac5-9850-d3f7b8432e87",
        "browserName": "safari",
        "platform": "OS X 10.11",
        "version": "8.1"
    }]
}
