### ISSUE TITLE
Multibrowser: error in report's layout

### ISSUE THREAD

**Issue by alaiaf** [brunoscopelliti/marvin#9]
Sometimes the generated report doesn't display the tabs for the various browser's results but paginates them with bullet points.

See attached screenshots.

![report_ok](https://cloud.githubusercontent.com/assets/12527850/10847365/3423e226-7f16-11e5-9ace-f80df4351b5e.png)
![report_ko](https://cloud.githubusercontent.com/assets/12527850/10847366/34dcf3ec-7f16-11e5-88b0-6c048377d261.png)

**Comment by verlok** [comment]
Can you report some steps to reproduce the bug?
Or it just happens randomly?

--
Andrea Verlicchi
www.andreaverlicchi.eu

**Comment by alaiaf** [comment]
It just happens randomly, if you want i can send you a report with this bug.

**Comment by brunoscopelliti** [comment]
@alaiaf yes, please

**Comment by brunoscopelliti** [comment]
We never reproduced this issue...
We use grunt, grunt-cotrib-sass to generate the report css... Handlebar to generate the view.

I checked the report you've sent...
The view is ok, and in the css the style of the tab is missing... strange!

**Comment by brunoscopelliti** [comment]
Re-installed marvin-js.
The issue isn't present anymore.
